/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DevStubIndexRouteImport } from './routes/dev/stub/index'
import { Route as DevMessageIndexRouteImport } from './routes/dev/message/index'
import { Route as DevLoginIndexRouteImport } from './routes/dev/login/index'
import { Route as DevCreateIndexRouteImport } from './routes/dev/create/index'
import { Route as DevBoardsheetIndexRouteImport } from './routes/dev/boardsheet/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DevStubIndexRoute = DevStubIndexRouteImport.update({
  id: '/dev/stub/',
  path: '/dev/stub/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMessageIndexRoute = DevMessageIndexRouteImport.update({
  id: '/dev/message/',
  path: '/dev/message/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLoginIndexRoute = DevLoginIndexRouteImport.update({
  id: '/dev/login/',
  path: '/dev/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevCreateIndexRoute = DevCreateIndexRouteImport.update({
  id: '/dev/create/',
  path: '/dev/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevBoardsheetIndexRoute = DevBoardsheetIndexRouteImport.update({
  id: '/dev/boardsheet/',
  path: '/dev/boardsheet/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dev/boardsheet/': typeof DevBoardsheetIndexRoute
  '/dev/create/': typeof DevCreateIndexRoute
  '/dev/login/': typeof DevLoginIndexRoute
  '/dev/message/': typeof DevMessageIndexRoute
  '/dev/stub/': typeof DevStubIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dev/boardsheet': typeof DevBoardsheetIndexRoute
  '/dev/create': typeof DevCreateIndexRoute
  '/dev/login': typeof DevLoginIndexRoute
  '/dev/message': typeof DevMessageIndexRoute
  '/dev/stub': typeof DevStubIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dev/boardsheet/': typeof DevBoardsheetIndexRoute
  '/dev/create/': typeof DevCreateIndexRoute
  '/dev/login/': typeof DevLoginIndexRoute
  '/dev/message/': typeof DevMessageIndexRoute
  '/dev/stub/': typeof DevStubIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dev/boardsheet/'
    | '/dev/create/'
    | '/dev/login/'
    | '/dev/message/'
    | '/dev/stub/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dev/boardsheet'
    | '/dev/create'
    | '/dev/login'
    | '/dev/message'
    | '/dev/stub'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dev/boardsheet/'
    | '/dev/create/'
    | '/dev/login/'
    | '/dev/message/'
    | '/dev/stub/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  DevBoardsheetIndexRoute: typeof DevBoardsheetIndexRoute
  DevCreateIndexRoute: typeof DevCreateIndexRoute
  DevLoginIndexRoute: typeof DevLoginIndexRoute
  DevMessageIndexRoute: typeof DevMessageIndexRoute
  DevStubIndexRoute: typeof DevStubIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dev/stub/': {
      id: '/dev/stub/'
      path: '/dev/stub'
      fullPath: '/dev/stub/'
      preLoaderRoute: typeof DevStubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/message/': {
      id: '/dev/message/'
      path: '/dev/message'
      fullPath: '/dev/message/'
      preLoaderRoute: typeof DevMessageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/login/': {
      id: '/dev/login/'
      path: '/dev/login'
      fullPath: '/dev/login/'
      preLoaderRoute: typeof DevLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/create/': {
      id: '/dev/create/'
      path: '/dev/create'
      fullPath: '/dev/create/'
      preLoaderRoute: typeof DevCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/boardsheet/': {
      id: '/dev/boardsheet/'
      path: '/dev/boardsheet'
      fullPath: '/dev/boardsheet/'
      preLoaderRoute: typeof DevBoardsheetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  DevBoardsheetIndexRoute: DevBoardsheetIndexRoute,
  DevCreateIndexRoute: DevCreateIndexRoute,
  DevLoginIndexRoute: DevLoginIndexRoute,
  DevMessageIndexRoute: DevMessageIndexRoute,
  DevStubIndexRoute: DevStubIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
