/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as SupportIndexRouteImport } from './routes/support/index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppTodayIndexRouteImport } from './routes/_app/today/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppLinksIndexRouteImport } from './routes/_app/links/index'
import { Route as AppSettingsWarpRouteImport } from './routes/_app/settings/warp'
import { Route as AppLinksNewRouteImport } from './routes/_app/links/new'
import { Route as AppLinksLinkIdRouteImport } from './routes/_app/links/$linkId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTodayIndexRoute = AppTodayIndexRouteImport.update({
  id: '/today/',
  path: '/today/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppLinksIndexRoute = AppLinksIndexRouteImport.update({
  id: '/links/',
  path: '/links/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsWarpRoute = AppSettingsWarpRouteImport.update({
  id: '/settings/warp',
  path: '/settings/warp',
  getParentRoute: () => AppRoute,
} as any)
const AppLinksNewRoute = AppLinksNewRouteImport.update({
  id: '/links/new',
  path: '/links/new',
  getParentRoute: () => AppRoute,
} as any)
const AppLinksLinkIdRoute = AppLinksLinkIdRouteImport.update({
  id: '/links/$linkId',
  path: '/links/$linkId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/': typeof LoginIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/support/': typeof SupportIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/links/$linkId': typeof AppLinksLinkIdRoute
  '/links/new': typeof AppLinksNewRoute
  '/settings/warp': typeof AppSettingsWarpRoute
  '/links/': typeof AppLinksIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/today/': typeof AppTodayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/support': typeof SupportIndexRoute
  '/terms': typeof TermsIndexRoute
  '/links/$linkId': typeof AppLinksLinkIdRoute
  '/links/new': typeof AppLinksNewRoute
  '/settings/warp': typeof AppSettingsWarpRoute
  '/links': typeof AppLinksIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/today': typeof AppTodayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/support/': typeof SupportIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/_app/links/$linkId': typeof AppLinksLinkIdRoute
  '/_app/links/new': typeof AppLinksNewRoute
  '/_app/settings/warp': typeof AppSettingsWarpRoute
  '/_app/links/': typeof AppLinksIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/today/': typeof AppTodayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/privacy/'
    | '/support/'
    | '/terms/'
    | '/links/$linkId'
    | '/links/new'
    | '/settings/warp'
    | '/links/'
    | '/settings/'
    | '/today/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/links/$linkId'
    | '/links/new'
    | '/settings/warp'
    | '/links'
    | '/settings'
    | '/today'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login/'
    | '/privacy/'
    | '/support/'
    | '/terms/'
    | '/_app/links/$linkId'
    | '/_app/links/new'
    | '/_app/settings/warp'
    | '/_app/links/'
    | '/_app/settings/'
    | '/_app/today/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/today/': {
      id: '/_app/today/'
      path: '/today'
      fullPath: '/today/'
      preLoaderRoute: typeof AppTodayIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/links/': {
      id: '/_app/links/'
      path: '/links'
      fullPath: '/links/'
      preLoaderRoute: typeof AppLinksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/warp': {
      id: '/_app/settings/warp'
      path: '/settings/warp'
      fullPath: '/settings/warp'
      preLoaderRoute: typeof AppSettingsWarpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/links/new': {
      id: '/_app/links/new'
      path: '/links/new'
      fullPath: '/links/new'
      preLoaderRoute: typeof AppLinksNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/links/$linkId': {
      id: '/_app/links/$linkId'
      path: '/links/$linkId'
      fullPath: '/links/$linkId'
      preLoaderRoute: typeof AppLinksLinkIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppLinksLinkIdRoute: typeof AppLinksLinkIdRoute
  AppLinksNewRoute: typeof AppLinksNewRoute
  AppSettingsWarpRoute: typeof AppSettingsWarpRoute
  AppLinksIndexRoute: typeof AppLinksIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppTodayIndexRoute: typeof AppTodayIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLinksLinkIdRoute: AppLinksLinkIdRoute,
  AppLinksNewRoute: AppLinksNewRoute,
  AppSettingsWarpRoute: AppSettingsWarpRoute,
  AppLinksIndexRoute: AppLinksIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppTodayIndexRoute: AppTodayIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
