/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StubIndexRouteImport } from './routes/stub/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as BoardsheetIndexRouteImport } from './routes/boardsheet/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StubIndexRoute = StubIndexRouteImport.update({
  id: '/stub/',
  path: '/stub/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsheetIndexRoute = BoardsheetIndexRouteImport.update({
  id: '/boardsheet/',
  path: '/boardsheet/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boardsheet/': typeof BoardsheetIndexRoute
  '/login/': typeof LoginIndexRoute
  '/stub/': typeof StubIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boardsheet': typeof BoardsheetIndexRoute
  '/login': typeof LoginIndexRoute
  '/stub': typeof StubIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boardsheet/': typeof BoardsheetIndexRoute
  '/login/': typeof LoginIndexRoute
  '/stub/': typeof StubIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/boardsheet/' | '/login/' | '/stub/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boardsheet' | '/login' | '/stub'
  id: '__root__' | '/' | '/boardsheet/' | '/login/' | '/stub/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsheetIndexRoute: typeof BoardsheetIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  StubIndexRoute: typeof StubIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stub/': {
      id: '/stub/'
      path: '/stub'
      fullPath: '/stub/'
      preLoaderRoute: typeof StubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boardsheet/': {
      id: '/boardsheet/'
      path: '/boardsheet'
      fullPath: '/boardsheet/'
      preLoaderRoute: typeof BoardsheetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsheetIndexRoute: BoardsheetIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  StubIndexRoute: StubIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
